### ISSUE TITLE
一覧画面のレイアウト

### ISSUE THREAD

**Issue by ToboMasaya** [kiesproject/yabamiru#2]
### 担当
西向

**Comment by pikohan-suzuki** [comment]
## イメージ
![iOS の画像 (21)](https://user-images.githubusercontent.com/29095003/60379396-3272ae00-9a6d-11e9-96d2-94ecc08387c4.jpg)

## 備考とか  
 - リストの中のCardは他のレイアウトファイルで作るから、RecyclerViewだけのっけとくかんじで
