### ISSUE TITLE
developのビルドエラー

### ISSUE THREAD

**Issue by hayasitakumi** [kiesproject/yabamiru#24]
## ビルドエラー
僕（林）のブランチをマージしたdevelopブランチでテストしたところビルドエラーが起こりました。
**build.gradle**の`implementation 'com.google.android.material:material:1.0.0'`をコメントアウトするとビルドできるようになったので報告しておきます。

このライブラリを追加した人はどこに使ったか以下にコメントしてください。
あと修正案とかもコメントしてくれるとありがたいです。

**Comment by pikohan-suzuki** [comment]
implementation 'com.google.android.material:material:1.0.0'の行を削除で問題ないと思う

これが何のパッケージか調べたら、ActionBarのデザイン関連のやつみたい。
ひとまず、使う予定はないから削除でいいかと。

**Comment by ToboMasaya** [comment]
これ僕がタブを作るときに、build.gradleに追加しろとサイトに書いてあったやつで、間違えてdevelopにpullしちゃったのがもともとでした。迷惑かけてごめんなさい。
